#!/usr/bin/env node
/* Convertze site generator.
 *
 * Reads data/tools.json and writes:
 *   - index.html                  (homepage: search + recent + categorized directory)
 *   - <cat>/index.html            (3 category hubs)
 *   - <cat>/<tool>/index.html     (27 tool pages)
 *   - 404.html, sitemap.xml
 *
 * Usage: node scripts/generate.js
 * Pages carry a marker comment; edit data/tools.json or this template and re-run.
 */
"use strict";

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.join(__dirname, "..");
// Content hash of the shared assets. Used to version asset URLs and the
// service worker cache so stale CSS/JS can never be served against new HTML.
const ASSET_FILES = ["site.css", "app.js", "tools-image.js", "tools-pdf.js", "tools-dev.js", "tools-text.js", "tools-calc.js"];
const ASSET_HASH = crypto.createHash("md5")
  .update(ASSET_FILES.map((f) => fs.readFileSync(path.join(__dirname, "..", "assets", f))).join("\n"))
  .digest("hex").slice(0, 8);
const v = (assetPath) => `${assetPath}?v=${ASSET_HASH}`;
const DATA = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "tools.json"), "utf8"));
const SITE = DATA.site.replace(/\/$/, "");
const TODAY = new Date().toISOString().slice(0, 10);
const MARK = "<!-- GENERATED by scripts/generate.js, edit data/tools.json and re-run. -->";

const LIB_URLS = {
  jszip: "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js",
  jspdf: "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js",
  html2canvas: "https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js",
  pdfjs: "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js",
  pdflib: "https://cdnjs.cloudflare.com/ajax/libs/pdf-lib/1.17.1/pdf-lib.min.js",
  jsyaml: "https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js",
  marked: "https://cdnjs.cloudflare.com/ajax/libs/marked/9.1.6/marked.min.js",
  sparkmd5: "https://cdnjs.cloudflare.com/ajax/libs/spark-md5/3.0.2/spark-md5.min.js",
  qrcode: "https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js",
  heic2any: "https://cdnjs.cloudflare.com/ajax/libs/heic2any/0.0.4/heic2any.min.js",
  tesseract: "https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/5.1.1/tesseract.min.js",
  sqlformatter: "https://cdnjs.cloudflare.com/ajax/libs/sql-formatter/15.3.2/sql-formatter.min.js",
  mammoth: "https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.8.0/mammoth.browser.min.js",
  piexif: "https://cdnjs.cloudflare.com/ajax/libs/piexifjs/1.0.6/piexif.min.js"
};
const CAT_MODULE = { images: "tools-image.js", pdf: "tools-pdf.js", dev: "tools-dev.js", text: "tools-text.js", calc: "tools-calc.js" };

const esc = (s) => String(s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const cats = DATA.categories;
const tools = DATA.tools;
const byPath = Object.fromEntries(tools.map((t) => [t.path, t]));
const byCat = Object.fromEntries(cats.map((c) => [c.id, tools.filter((t) => t.cat === c.id)]));

const TOOL_INDEX = JSON.stringify(tools.map((t) => ({ p: t.path, n: t.name, s: t.short })));

const ICONS = {
  search: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="7"/><line x1="21" y1="21" x2="16.5" y2="16.5"/></svg>',
  github: '<svg width="16" height="16" viewBox="0 0 98 96" fill="currentColor" aria-hidden="true"><path fill-rule="evenodd" clip-rule="evenodd" d="M48.854 0C21.839 0 0 22 0 49.217c0 21.756 13.993 40.172 33.405 46.69 2.427.49 3.316-1.059 3.316-2.362 0-1.141-.08-5.052-.08-9.127-13.59 2.934-16.42-5.867-16.42-5.867-2.184-5.704-5.42-7.17-5.42-7.17-4.448-3.015.324-3.015.324-3.015 4.934.326 7.523 5.052 7.523 5.052 4.367 7.496 11.404 5.378 14.235 4.074.404-3.178 1.699-5.378 3.074-6.6-10.839-1.141-22.243-5.378-22.243-24.283 0-5.378 1.94-9.778 5.014-13.2-.485-1.222-2.184-6.275.486-13.038 0 0 4.125-1.304 13.426 5.052a46.97 46.97 0 0 1 12.214-1.63c4.125 0 8.33.571 12.213 1.63 9.302-6.356 13.427-5.052 13.427-5.052 2.67 6.763.97 11.816.485 13.038 3.155 3.422 5.015 7.822 5.015 13.2 0 18.905-11.404 23.06-22.324 24.283 1.78 1.548 3.316 4.481 3.316 9.126 0 6.6-.08 11.897-.08 13.526 0 1.304.89 2.853 3.316 2.364 19.412-6.52 33.405-24.935 33.405-46.691C97.707 22 75.788 0 48.854 0z"/></svg>',
  sun: '<svg class="sun" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>',
  moon: '<svg class="moon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg>',
  shield: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><polyline points="9 12 11 14 15 10"/></svg>'
};

/* Per-tool icons (lucide-style strokes). Explicit width/height so they stay
   small even if the stylesheet hasn't loaded yet. */
const stroke = (inner) => `<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${inner}</svg>`;
const TOOL_ICONS = {
  image: stroke('<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/>'),
  swap: stroke('<polyline points="17 1 21 5 17 9"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><polyline points="7 23 3 19 7 15"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/>'),
  maximize: stroke('<polyline points="15 3 21 3 21 9"/><polyline points="9 21 3 21 3 15"/><line x1="21" y1="3" x2="14" y2="10"/><line x1="3" y1="21" x2="10" y2="14"/>'),
  minimize: stroke('<polyline points="4 14 10 14 10 20"/><polyline points="20 10 14 10 14 4"/><line x1="14" y1="10" x2="21" y2="3"/><line x1="3" y1="21" x2="10" y2="14"/>'),
  crop: stroke('<path d="M6 2v14a2 2 0 0 0 2 2h14"/><path d="M18 22V8a2 2 0 0 0-2-2H2"/>'),
  rotate: stroke('<polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/>'),
  star: stroke('<polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>'),
  layers: stroke('<polygon points="12 2 2 7 12 12 22 7 12 2"/><polyline points="2 17 12 22 22 17"/><polyline points="2 12 12 17 22 12"/>'),
  files: stroke('<rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>'),
  scissors: stroke('<circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><line x1="20" y1="4" x2="8.12" y2="15.88"/><line x1="14.47" y1="14.48" x2="20" y2="20"/><line x1="8.12" y1="8.12" x2="12" y2="12"/>'),
  archive: stroke('<polyline points="21 8 21 21 3 21 3 8"/><rect x="1" y="3" width="22" height="5" rx="1"/><line x1="10" y1="12" x2="14" y2="12"/>'),
  filetext: stroke('<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/>'),
  code: stroke('<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>'),
  braces: stroke('<path d="M8 3H7a2 2 0 0 0-2 2v5a2 2 0 0 1-2 2 2 2 0 0 1 2 2v5c0 1.1.9 2 2 2h1"/><path d="M16 21h1a2 2 0 0 0 2-2v-5c0-1.1.9-2 2-2a2 2 0 0 1-2-2V5a2 2 0 0 0-2-2h-1"/>'),
  table: stroke('<rect x="3" y="3" width="18" height="18" rx="2"/><line x1="3" y1="9" x2="21" y2="9"/><line x1="9" y1="21" x2="9" y2="9"/>'),
  key: stroke('<path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m3 3L22 7l-3-3"/>'),
  hash: stroke('<line x1="4" y1="9" x2="20" y2="9"/><line x1="4" y1="15" x2="20" y2="15"/><line x1="10" y1="3" x2="8" y2="21"/><line x1="16" y1="3" x2="14" y2="21"/>'),
  clock: stroke('<circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>'),
  diff: stroke('<circle cx="18" cy="18" r="3"/><circle cx="6" cy="6" r="3"/><path d="M13 6h3a2 2 0 0 1 2 2v7"/><path d="M11 18H8a2 2 0 0 1-2-2V9"/>'),
  asterisk: stroke('<line x1="12" y1="3" x2="12" y2="21"/><line x1="5.6" y1="7.5" x2="18.4" y2="16.5"/><line x1="18.4" y1="7.5" x2="5.6" y2="16.5"/>'),
  droplet: stroke('<path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z"/>'),
  link: stroke('<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>'),
  eye: stroke('<path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/>'),
  qr: stroke('<rect x="3" y="3" width="5" height="5"/><rect x="16" y="3" width="5" height="5"/><rect x="3" y="16" width="5" height="5"/><path d="M21 16h-3a2 2 0 0 0-2 2v3"/><path d="M21 21v.01"/><path d="M12 7v3a2 2 0 0 1-2 2H7"/><path d="M3 12h.01"/><path d="M12 3h.01"/><path d="M12 16v.01"/><path d="M16 12h1"/><path d="M21 12v.01"/><path d="M12 21v-1"/>'),
  type: stroke('<polyline points="4 7 4 4 20 4 20 7"/><line x1="9" y1="20" x2="15" y2="20"/><line x1="12" y1="4" x2="12" y2="20"/>'),
  sort: stroke('<path d="M11 5h10"/><path d="M11 9h7"/><path d="M11 13h4"/><path d="M3 17l3 3 3-3"/><path d="M6 20V4"/>'),
  quote: stroke('<path d="M3 21c3 0 7-1 7-8V5c0-1.25-.756-2.017-2-2H4c-1.25 0-2 .75-2 1.972V11c0 1.25.75 2 2 2 1 0 1 0 1 1v1c0 1-1 2-2 2s-1 .008-1 1.031V20c0 1 0 1 1 1z"/><path d="M15 21c3 0 7-1 7-8V5c0-1.25-.757-2.017-2-2h-4c-1.25 0-2 .75-2 1.972V11c0 1.25.75 2 2 2h.75c0 2.25.25 4-2.75 4v3c0 1 0 1 1 1z"/>'),
  pen: stroke('<path d="M12 19l7-7 3 3-7 7-3-3z"/><path d="M18 13l-1.5-7.5L2 2l3.5 14.5L13 18l5-5z"/><path d="M2 2l7.586 7.586"/><circle cx="11" cy="11" r="2"/>'),
  currency: stroke('<circle cx="12" cy="12" r="10"/><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/><path d="M12 18V6"/>'),
  ruler: stroke('<path d="M21.3 15.3a2.4 2.4 0 0 1 0 3.4l-2.6 2.6a2.4 2.4 0 0 1-3.4 0L2.7 8.7a2.4 2.4 0 0 1 0-3.4l2.6-2.6a2.4 2.4 0 0 1 3.4 0z"/><path d="m14.5 12.5 2-2"/><path d="m11.5 9.5 2-2"/><path d="m8.5 6.5 2-2"/><path d="m17.5 15.5 2-2"/>'),
  scale: stroke('<path d="m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1z"/><path d="m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1z"/><path d="M7 21h10"/><path d="M12 3v18"/><path d="M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2"/>'),
  thermometer: stroke('<path d="M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0z"/>'),
  gridicon: stroke('<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18"/><path d="M3 15h18"/><path d="M9 3v18"/><path d="M15 3v18"/>'),
  gauge: stroke('<path d="m12 14 4-4"/><path d="M3.34 19a10 10 0 1 1 17.32 0"/>'),
  database: stroke('<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5V19A9 3 0 0 0 21 19V5"/><path d="M3 12A9 3 0 0 0 21 12"/>'),
  percent: stroke('<line x1="19" y1="5" x2="5" y2="19"/><circle cx="6.5" cy="6.5" r="2.5"/><circle cx="17.5" cy="17.5" r="2.5"/>'),
  calendar: stroke('<rect x="3" y="4" width="18" height="18" rx="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/>'),
  coins: stroke('<circle cx="8" cy="8" r="6"/><path d="M18.09 10.37A6 6 0 1 1 10.34 18"/><path d="M7 6h1v4"/><path d="m16.71 13.88.7.71-2.82 2.82"/>'),
  receipt: stroke('<path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1z"/><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/><path d="M12 17.5v-11"/>'),
  heart: stroke('<path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7z"/>'),
  scan: stroke('<path d="M3 7V5a2 2 0 0 1 2-2h2"/><path d="M17 3h2a2 2 0 0 1 2 2v2"/><path d="M21 17v2a2 2 0 0 1-2 2h-2"/><path d="M7 21H5a2 2 0 0 1-2-2v-2"/><line x1="7" y1="12" x2="17" y2="12"/>'),
  stamp: stroke('<path d="M5 22h14"/><path d="M19.27 13.73A2.5 2.5 0 0 0 17.5 13h-11A2.5 2.5 0 0 0 4 15.5V17a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-1.5c0-.66-.26-1.3-.73-1.77z"/><path d="M14 13V8.5C14 7 15 7 15 5a3 3 0 0 0-6 0c0 2 1 2 1 3.5V13"/>')
};
const toolIcon = (t, lg) =>
  `<span class="t-icon${lg ? " lg" : ""} c-${t.cat}">${TOOL_ICONS[t.icon] || TOOL_ICONS.image}</span>`;

function head({ title, desc, canonicalPath, ogImage, is404 }) {
  const url = canonicalPath ? `${SITE}/${canonicalPath}` : `${SITE}/`;
  const og = `${SITE}${ogImage || "/assets/og/default.png"}`;
  // On the 404 page, count the path that actually failed (as "404-/bad/url")
  // instead of the canonical, so broken links show up in the dashboard.
  const gc = DATA.goatcounter
    ? `${is404 ? '\n  <script>window.goatcounter={path:function(){return "404-"+location.pathname+location.search}};</script>' : ""}\n  <script data-goatcounter="https://${DATA.goatcounter}.goatcounter.com/count" async src="https://gc.zgo.at/count.js"></script>`
    : "";
  return `<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(desc)}">
  <meta name="robots" content="${is404 ? "noindex, follow" : "index, follow"}">${is404 ? "" : `
  <link rel="canonical" href="${url}">`}
  <link rel="icon" type="image/svg+xml" href="/favicon.svg">
  <link rel="manifest" href="/manifest.webmanifest">
  <meta name="theme-color" content="#0f172a">
  <meta property="og:type" content="website">
  <meta property="og:url" content="${url}">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(desc)}">
  <meta property="og:site_name" content="Convertze">
  <meta property="og:image" content="${og}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:image" content="${og}">${gc}
  <script>try{if(localStorage.getItem("convertze-theme")==="light")document.documentElement.classList.add("light")}catch(e){}</script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="${v("/assets/site.css")}">
  <script>window.TOOL_INDEX=${TOOL_INDEX};</script>
</head>`;
}

function header(activeCat) {
  const nav = cats.map((c) =>
    `<a href="/${c.id}"${activeCat === c.id ? ' aria-current="true"' : ""}>${esc(c.nav)}</a>`
  ).join("");
  return `<header class="site-header">
    <div class="wrap bar">
      <a class="brand" href="/"><span class="brand-mark">C</span><b>Convertze</b></a>
      <nav class="nav-links" aria-label="Categories">${nav}</nav>
      <span class="header-spacer"></span>
      <div class="header-search" data-tool-search>
        ${ICONS.search}
        <input type="text" placeholder="Search tools...   Ctrl+K" aria-label="Search tools">
        <div class="search-pop"></div>
      </div>
      <a class="icon-btn" href="https://github.com/harsh-m-10/convertze" target="_blank" rel="noopener noreferrer" aria-label="View source on GitHub" title="Open source on GitHub">${ICONS.github}</a>
      <button class="icon-btn" id="theme-toggle" type="button" aria-label="Toggle dark and light mode">${ICONS.sun}${ICONS.moon}</button>
    </div>
  </header>`;
}

function footer() {
  return `<footer class="site-footer">
    <div class="wrap foot-grid">
      <div class="foot-brand">
        <a class="brand" href="/"><span class="brand-mark">C</span><b>Convertze</b></a>
        <p>Free, open source tools that run in your browser. Your files never leave your device.</p>
        <button class="mini" id="install-app" type="button" style="display:none">Install app</button>
      </div>
      <nav class="foot-col" aria-label="Tool categories">
        <h4>Tools</h4>
        ${cats.map((c) => `<a href="/${c.id}">${esc(c.label)}</a>`).join("\n        ")}
      </nav>
      <nav class="foot-col" aria-label="Site">
        <h4>Site</h4>
        <a href="/about">About</a>
        <a href="/changelog">What's new</a>
        <a href="/about#feedback">Feedback & requests</a>
        <a href="https://github.com/harsh-m-10/convertze" rel="noopener noreferrer" target="_blank">GitHub</a>
      </nav>
    </div>
  </footer>`;
}

// The privacy line adapts to the category: image and PDF tools handle files,
// while text, dev and calculator tools work on text and numbers you type.
function privacyBadge(cat) {
  const line = (cat === "images" || cat === "pdf")
    ? "Files stay on your device. No accounts. Free."
    : "Everything runs on your device. No accounts. Free.";
  return `<p class="privacy-line">${ICONS.shield} ${line}</p>`;
}

/* Feedback / feature request form (about + changelog). Posts to Web3Forms so
 * there is still no Convertze server; renders a GitHub fallback until the
 * access key is set in data/tools.json. */
function feedbackPanel(heading, lead) {
  heading = heading || "Request a tool, report a bug, or just say something";
  lead = lead || "Not everyone wants a GitHub account, so here is a plain form. Feature requests genuinely drive the roadmap, and bug reports get fixed fast.";
  if (!DATA.web3forms) {
    return `<div class="panel about" id="feedback">
          <h2>${esc(heading)}</h2>
          <p>The feedback form is warming up. In the meantime, <a href="https://github.com/harsh-m-10/convertze/issues/new" rel="noopener noreferrer" target="_blank">open a GitHub issue</a>, several tools on this site exist because someone did.</p>
        </div>`;
  }
  return `<div class="panel about" id="feedback">
          <h2>${esc(heading)}</h2>
          <p>${esc(lead)}</p>
          <form data-feedback novalidate>
            <input type="hidden" name="access_key" value="${esc(DATA.web3forms)}">
            <input type="hidden" name="subject" value="Convertze feedback">
            <input type="hidden" name="from_name" value="Convertze feedback form">
            <input type="checkbox" name="botcheck" class="fb-hp" tabindex="-1" autocomplete="off" aria-hidden="true">
            <div class="fb-row">
              <label class="field fb-field">Name <input type="text" name="name" placeholder="What should we call you?"></label>
              <label class="field fb-field">Email <input type="text" name="email" inputmode="email" placeholder="Only if you want a reply"></label>
              <label class="field fb-field">Type <select name="type"><option>Feature request</option><option>Bug or error</option><option>Feedback</option><option>Complaint</option></select></label>
            </div>
            <textarea class="ta fb-ta" name="message" rows="4" placeholder="What do you need, or what went wrong? If it is a bug, the tool name and what you dropped into it help a lot." aria-label="Your message"></textarea>
            <div class="actions-row"><button class="btn" type="submit">Send it</button><span class="fb-status" role="status"></span></div>
          </form>
          <p class="fb-note">Honest note: this form is the one thing on this page that sends anything anywhere. Exactly what you type above goes to our inbox via Web3Forms, nothing else does.</p>
        </div>`;
}

function page({ title, desc, canonicalPath, activeCat, body, scripts, ogImage, is404 }) {
  return `<!DOCTYPE html>
${MARK}
<html lang="en">
${head({ title, desc, canonicalPath, ogImage, is404 })}
<body>
  ${header(activeCat)}
  ${body}
  ${footer()}
  <script src="${v("/assets/app.js")}" defer></script>
${(scripts || []).map((s) => `  <script src="${s}" defer></script>`).join("\n")}
</body>
</html>
`;
}

/* ---------- Homepage ---------- */
function homepage() {
  const sections = cats.map((c) => {
    const cards = byCat[c.id].map((t) =>
      `<a class="tool-card" data-name="${esc((t.name + " " + t.short).toLowerCase())}" href="/${t.path}">${toolIcon(t)}<span class="t-text"><b>${esc(t.name)}</b><span>${esc(t.short)}</span></span></a>`
    ).join("\n        ");
    return `<section class="cat-section">
      <div class="cat-head">
        <h2><a href="/${c.id}">${esc(c.label)}</a></h2>
        <p>${esc(c.blurb)}</p>
      </div>
      <div class="grid">
        ${cards}
      </div>
    </section>`;
  }).join("\n    ");

  const body = `<main class="wrap">
    <section class="hero">
      <h1>Convert anything.<br><span class="grad">Nothing leaves your device.</span></h1>
      <p>Free, fast tools for images, PDFs, text and everyday dev work. Everything runs right here in your browser, so your files never leave your hands.</p>
      <span class="trust-badge">${ICONS.shield} Files stay on your device · Works offline · Open source</span>
    </section>
    <div class="header-search" style="max-width:430px;margin:18px 0 6px">
      ${ICONS.search}
      <input type="text" id="grid-search" placeholder="Search ${tools.length} tools..." aria-label="Search tools" style="width:100%">
    </div>
    <p class="no-results">No tools match that search.</p>
    <section class="cat-section" id="recent-tools" style="display:none">
      <div class="cat-head"><h2>Pick up where you left off</h2></div>
      <div class="grid"></div>
    </section>
    ${sections}
  </main>`;

  return page({
    title: "Convertze, Free & Private Online File, Text & Developer Tools",
    desc: "Free in-browser tools: convert and compress images, merge and split PDFs, count words, format JSON, decode JWTs and more. Your files stay on your device.",
    canonicalPath: "",
    body
  });
}

/* ---------- Category hubs ---------- */
function hubPage(cat) {
  const cards = byCat[cat.id].map((t) =>
    `<a class="tool-card" href="/${t.path}">${toolIcon(t)}<span class="t-text"><b>${esc(t.name)}</b><span>${esc(t.short)}</span></span></a>`
  ).join("\n      ");
  const others = cats.filter((c) => c.id !== cat.id)
    .map((c) => `<a href="/${c.id}">${esc(c.label)}</a>`).join(" · ");
  const body = `<main class="wrap">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> › ${esc(cat.label)}</nav>
    <h1 class="tool-h1">${esc(cat.label)}</h1>
    <p class="tool-tagline">${esc(cat.blurb)}</p>
    ${privacyBadge(cat.id)}
    <div class="grid" style="margin-top:8px">
      ${cards}
    </div>
    <p style="margin-top:26px;color:var(--muted);font-size:13.5px">More: ${others}</p>
  </main>`;
  return page({
    title: `${cat.label}, Free & Private, In Your Browser | Convertze`,
    desc: cat.blurb + " Free and private, no sign-up.",
    canonicalPath: cat.id,
    activeCat: cat.id,
    body
  });
}

/* ---------- Tool pages ---------- */
const STEPS = {
  images: [
    "Drop one or more images, they stay on your device.",
    "Pick your options and convert.",
    "Download the result; multiple files arrive as a single zip."
  ],
  pdf: [
    "Drop your file(s), they are read locally on your device.",
    "Set the options you need and run the tool.",
    "Download the finished PDF, images or text."
  ],
  dev: [
    "Paste your input, or drop a text file onto the box.",
    "The output updates live as you type.",
    "Copy it to the clipboard, or download it as a file."
  ],
  text: [
    "Paste or type your text into the box.",
    "The results update live as you type.",
    "Copy the output, or download it as a file."
  ],
  calc: [
    "Enter your numbers and pick the options.",
    "The result updates live as you type.",
    "Everything is calculated on your device, nothing is saved or sent."
  ]
};

function toolPage(t) {
  const cat = cats.find((c) => c.id === t.cat);
  const siblings = byCat[t.cat].map((s) =>
    `<a href="/${s.path}"${s.path === t.path ? ' aria-current="true"' : ""}>${esc(s.name)}</a>`
  ).join("\n        ");
  const related = (t.related || []).filter((p) => byPath[p]).map((p) =>
    `<li><a href="/${p}">${esc(byPath[p].name)}</a> <span style="color:var(--muted);font-weight:400">- ${esc(byPath[p].short)}</span></li>`
  ).join("\n          ");
  const steps = (t.steps || STEPS[t.cat]).map((s) => `<li>${esc(s)}</li>`).join("\n          ");
  const libScripts = (t.libs || []).map((l) => LIB_URLS[l]);
  const jsonLd = JSON.stringify({
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: t.name,
    url: `${SITE}/${t.path}`,
    description: t.metaDescription,
    applicationCategory: "UtilitiesApplication",
    operatingSystem: "Any",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }
  });
  const faqs = t.faq || [];
  const faqPanel = faqs.length ? `<div class="panel">
          <h2>Frequently asked questions</h2>
          ${faqs.map((f) => `<details class="faq-item"><summary>${esc(f.q)}</summary><p>${esc(f.a)}</p></details>`).join("\n          ")}
        </div>
        ` : "";
  const faqLd = faqs.length ? `
  <script type="application/ld+json">${JSON.stringify({
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a }
    }))
  })}</script>` : "";

  const body = `<main class="wrap">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> › <a href="/${cat.id}">${esc(cat.label)}</a> › ${esc(t.name)}</nav>
    <div class="h1-row">${toolIcon(t, true)}<h1 class="tool-h1">${esc(t.h1)}</h1></div>
    <p class="tool-tagline">${esc(t.short)}</p>
    ${privacyBadge(t.cat)}
    <div class="page-grid">
      <div>
        <div class="panel" id="tool-root" data-tool="${t.path}">
          <noscript>This tool runs entirely in your browser and needs JavaScript enabled.</noscript>
          <p style="color:var(--muted);font-size:13.5px;margin:0">Loading tool...</p>
        </div>
        <div class="panel about">
          <h2>About this tool</h2>
          ${t.about.map((p) => `<p>${esc(p)}</p>`).join("\n          ")}
        </div>
        <div class="panel">
          <h2>How it works</h2>
          <ol class="steps">
          ${steps}
          </ol>
        </div>
        ${faqPanel}<div class="panel">
          <h2>Related tools</h2>
          <ul class="related-list">
          ${related}
          </ul>
          <p style="margin:14px 0 0;font-size:12.8px">Missing something, or found a bug? <a href="https://github.com/harsh-m-10/convertze/issues/new?title=${encodeURIComponent("[" + t.name + "] ")}" rel="noopener noreferrer" target="_blank">Open a GitHub issue</a> or <a href="/about#feedback">use the feedback form</a>, no account needed.</p>
        </div>
      </div>
      <aside class="side-nav" aria-label="${esc(cat.label)}">
        <h3>${esc(cat.label)}</h3>
        ${siblings}
      </aside>
    </div>
  </main>
  <script type="application/ld+json">${jsonLd}</script>${faqLd}`;

  return page({
    title: `${t.name}, Free & Private, In Your Browser | Convertze`,
    desc: t.metaDescription,
    canonicalPath: t.path,
    activeCat: t.cat,
    ogImage: `/assets/og/${t.path.replace("/", "-")}.png`,
    body,
    scripts: [...libScripts, v("/assets/" + CAT_MODULE[t.cat])]
  });
}

/* ---------- 404 ---------- */
function notFound() {
  const body = `<main class="wrap">
    <div class="err-page">
      <h1>404</h1>
      <p>That page doesn't exist, but the tool you wanted probably does.</p>
      <div class="header-search" data-tool-search>
        ${ICONS.search}
        <input type="text" placeholder="Search tools...   Ctrl+K" aria-label="Search tools">
        <div class="search-pop"></div>
      </div>
      <p style="margin-top:18px"><a class="btn" href="/">Browse all tools</a></p>
    </div>
    <div class="page-grid" style="grid-template-columns:minmax(0,720px);justify-content:center;margin-top:6px">
      <div>
        ${feedbackPanel(
          "And if the tool you wanted doesn't exist yet, ask for it",
          "Tell us what you were looking for and there is a real chance it ships within days. Several tools on this site exist because someone asked."
        )}
      </div>
    </div>
  </main>`;
  return page({
    title: "Page not found, Convertze",
    desc: "That page doesn't exist. Search Convertze's free in-browser file and developer tools.",
    canonicalPath: "404.html",
    is404: true,
    body
  });
}

/* ---------- About ---------- */
function aboutPage() {
  const body = `<main class="wrap">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> › About</nav>
    <h1 class="tool-h1" style="text-align:center">About Convertze</h1>
    <div class="page-grid" style="grid-template-columns:minmax(0,720px);justify-content:center">
      <div>
        <div class="panel about">
          <h2>What this is</h2>
          <p>Convertze is a free collection of ${tools.length} file, text and developer tools built by Agent Null as an open source side project. Every tool runs entirely inside your browser: images are converted by your browser's own canvas, PDFs are read and rebuilt by JavaScript libraries running in your tab, and text tools are plain local code.</p>
          <p>That architecture is the whole point. There is no server that receives your files, which means there is nothing to leak, nothing to retain, and no reason to make you sign up.</p>
        </div>
        <div class="panel about">
          <h2>The privacy promise, precisely</h2>
          <p>Your files, text and numbers never leave your device. A few tools download a shared, generic helper once so they can do their work: the currency converter fetches a public exchange-rate table, the image-to-text tool downloads its OCR engine, and the background remover downloads its segmentation model. None of these ever receive your content; only your own device does the work on it. You can verify all of this: open your browser's network tab while using any tool, or read the source code on GitHub.</p>
        </div>
        <div class="panel about">
          <h2>Contact & contributions</h2>
          <p>Found a bug, or missing a tool you need? Use the form below, or <a href="https://github.com/harsh-m-10/convertze/issues/new" rel="noopener noreferrer" target="_blank">open an issue on GitHub</a> if that is more your speed. Several tools on this site exist because someone asked for them.</p>
        </div>
        ${feedbackPanel()}
      </div>
    </div>
  </main>`;
  return page({
    title: "About Convertze, Free In-Browser Tools",
    desc: "Convertze is a free, open source collection of file, text and developer tools that run entirely in your browser. No uploads, no accounts, no tracking of your files.",
    canonicalPath: "about",
    body
  });
}

/* ---------- Changelog ---------- */
function changelogPage() {
  const log = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "changelog.json"), "utf8"));
  const entries = log.map((e) => `<div class="panel about">
          <h2>${esc(e.date)} · ${esc(e.title)}</h2>
          <ul class="related-list">
          ${e.items.map((i) => `<li>${esc(i)}</li>`).join("\n          ")}
          </ul>
        </div>`).join("\n        ");
  const body = `<main class="wrap">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> › What's new</nav>
    <h1 class="tool-h1" style="text-align:center">What's new</h1>
    <p class="tool-tagline" style="text-align:center">Everything shipped on Convertze, newest first.</p>
    <div class="page-grid" style="grid-template-columns:minmax(0,720px);justify-content:center">
      <div>
        ${entries}
        ${feedbackPanel()}
      </div>
    </div>
  </main>`;
  return page({
    title: "What's New on Convertze",
    desc: "Release notes for Convertze: new tools, features and fixes, newest first.",
    canonicalPath: "changelog",
    body
  });
}

/* ---------- Sitemap ---------- */
function sitemap() {
  const urls = [
    { loc: `${SITE}/`, pri: "1.0" },
    ...cats.map((c) => ({ loc: `${SITE}/${c.id}`, pri: "0.9" })),
    ...tools.map((t) => ({ loc: `${SITE}/${t.path}`, pri: "0.8" })),
    { loc: `${SITE}/about`, pri: "0.4" },
    { loc: `${SITE}/changelog`, pri: "0.4" }
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${TODAY}</lastmod>
    <priority>${u.pri}</priority>
  </url>`).join("\n")}
</urlset>
`;
}

/* ---------- main ---------- */
function write(rel, content) {
  const file = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  console.log("wrote " + rel);
}

write("index.html", homepage());
for (const c of cats) write(path.join(c.id, "index.html"), hubPage(c));
for (const t of tools) write(path.join(t.path, "index.html"), toolPage(t));
write(path.join("about", "index.html"), aboutPage());
write(path.join("changelog", "index.html"), changelogPage());
write("404.html", notFound());
write("sitemap.xml", sitemap());

// Re-stamp the service worker cache name so every deploy invalidates old caches.
const swPath = path.join(ROOT, "sw.js");
const sw = fs.readFileSync(swPath, "utf8");
fs.writeFileSync(swPath, sw.replace(/const CACHE_NAME = "[^"]+";/, `const CACHE_NAME = "convertze-${ASSET_HASH}";`));
console.log(`sw.js cache stamped: convertze-${ASSET_HASH}`);
console.log(`done: 1 home + ${cats.length} hubs + ${tools.length} tool pages + 404 + sitemap`);
