#!/usr/bin/env node
/* Convertze site generator.
 *
 * Reads data/tools.json and writes:
 *   - index.html                  (homepage: search + recent + categorized directory)
 *   - <cat>/index.html            (3 category hubs)
 *   - <cat>/<tool>/index.html     (27 tool pages)
 *   - 404.html, sitemap.xml
 *
 * Usage: node scripts/generate.js
 * Pages carry a marker comment; edit data/tools.json or this template and re-run.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DATA = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "tools.json"), "utf8"));
const SITE = DATA.site.replace(/\/$/, "");
const TODAY = new Date().toISOString().slice(0, 10);
const MARK = "<!-- GENERATED by scripts/generate.js, edit data/tools.json and re-run. -->";

const LIB_URLS = {
  jszip: "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js",
  jspdf: "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js",
  html2canvas: "https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js",
  pdfjs: "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js",
  pdflib: "https://cdnjs.cloudflare.com/ajax/libs/pdf-lib/1.17.1/pdf-lib.min.js",
  jsyaml: "https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js",
  marked: "https://cdnjs.cloudflare.com/ajax/libs/marked/9.1.6/marked.min.js",
  sparkmd5: "https://cdnjs.cloudflare.com/ajax/libs/spark-md5/3.0.2/spark-md5.min.js"
};
const CAT_MODULE = { images: "tools-image.js", pdf: "tools-pdf.js", dev: "tools-dev.js" };

const esc = (s) => String(s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const cats = DATA.categories;
const tools = DATA.tools;
const byPath = Object.fromEntries(tools.map((t) => [t.path, t]));
const byCat = Object.fromEntries(cats.map((c) => [c.id, tools.filter((t) => t.cat === c.id)]));

const TOOL_INDEX = JSON.stringify(tools.map((t) => ({ p: t.path, n: t.name, s: t.short })));

const ICONS = {
  search: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="7"/><line x1="21" y1="21" x2="16.5" y2="16.5"/></svg>',
  github: '<svg viewBox="0 0 98 96" fill="currentColor" aria-hidden="true"><path fill-rule="evenodd" clip-rule="evenodd" d="M48.854 0C21.839 0 0 22 0 49.217c0 21.756 13.993 40.172 33.405 46.69 2.427.49 3.316-1.059 3.316-2.362 0-1.141-.08-5.052-.08-9.127-13.59 2.934-16.42-5.867-16.42-5.867-2.184-5.704-5.42-7.17-5.42-7.17-4.448-3.015.324-3.015.324-3.015 4.934.326 7.523 5.052 7.523 5.052 4.367 7.496 11.404 5.378 14.235 4.074.404-3.178 1.699-5.378 3.074-6.6-10.839-1.141-22.243-5.378-22.243-24.283 0-5.378 1.94-9.778 5.014-13.2-.485-1.222-2.184-6.275.486-13.038 0 0 4.125-1.304 13.426 5.052a46.97 46.97 0 0 1 12.214-1.63c4.125 0 8.33.571 12.213 1.63 9.302-6.356 13.427-5.052 13.427-5.052 2.67 6.763.97 11.816.485 13.038 3.155 3.422 5.015 7.822 5.015 13.2 0 18.905-11.404 23.06-22.324 24.283 1.78 1.548 3.316 4.481 3.316 9.126 0 6.6-.08 11.897-.08 13.526 0 1.304.89 2.853 3.316 2.364 19.412-6.52 33.405-24.935 33.405-46.691C97.707 22 75.788 0 48.854 0z"/></svg>',
  sun: '<svg class="sun" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>',
  moon: '<svg class="moon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg>',
  shield: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><polyline points="9 12 11 14 15 10"/></svg>'
};

function head({ title, desc, canonicalPath }) {
  const url = canonicalPath ? `${SITE}/${canonicalPath}` : `${SITE}/`;
  return `<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(desc)}">
  <meta name="robots" content="index, follow">
  <link rel="canonical" href="${url}">
  <link rel="icon" type="image/svg+xml" href="/favicon.svg">
  <link rel="manifest" href="/manifest.webmanifest">
  <meta name="theme-color" content="#0f172a">
  <meta property="og:type" content="website">
  <meta property="og:url" content="${url}">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(desc)}">
  <meta property="og:site_name" content="Convertze">
  <meta name="twitter:card" content="summary">
  <script>try{if(localStorage.getItem("convertze-theme")==="light")document.documentElement.classList.add("light")}catch(e){}</script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/assets/site.css">
  <script>window.TOOL_INDEX=${TOOL_INDEX};</script>
</head>`;
}

function header(activeCat) {
  const nav = cats.map((c) =>
    `<a href="/${c.id}"${activeCat === c.id ? ' aria-current="true"' : ""}>${esc(c.nav)}</a>`
  ).join("");
  return `<header class="site-header">
    <div class="wrap bar">
      <a class="brand" href="/"><span class="brand-mark">C</span><b>Convertze</b></a>
      <nav class="nav-links" aria-label="Categories">${nav}</nav>
      <span class="header-spacer"></span>
      <div class="header-search" data-tool-search>
        ${ICONS.search}
        <input type="text" placeholder="Search tools..." aria-label="Search tools">
        <div class="search-pop"></div>
      </div>
      <a class="icon-btn" href="https://github.com/harsh-m-10/convertze" target="_blank" rel="noopener noreferrer" aria-label="View source on GitHub" title="Open source on GitHub">${ICONS.github}</a>
      <button class="icon-btn" id="theme-toggle" type="button" aria-label="Toggle dark and light mode">${ICONS.sun}${ICONS.moon}</button>
    </div>
  </header>`;
}

function footer() {
  return `<footer class="site-footer">
    <div class="wrap cols">
      <span>Convertze, free file &amp; developer tools. No uploads, no accounts: everything runs in your browser.</span>
      <span>${cats.map((c) => `<a href="/${c.id}">${esc(c.label)}</a>`).join(" · ")} · <a href="https://github.com/harsh-m-10/convertze" rel="noopener noreferrer" target="_blank">GitHub</a></span>
    </div>
  </footer>`;
}

const privacyBadge = `<p class="privacy-line">${ICONS.shield} No uploads. No accounts. Runs in your browser.</p>`;

function page({ title, desc, canonicalPath, activeCat, body, scripts }) {
  return `<!DOCTYPE html>
${MARK}
<html lang="en">
${head({ title, desc, canonicalPath })}
<body>
  ${header(activeCat)}
  ${body}
  ${footer()}
  <script src="/assets/app.js" defer></script>
${(scripts || []).map((s) => `  <script src="${s}" defer></script>`).join("\n")}
</body>
</html>
`;
}

/* ---------- Homepage ---------- */
function homepage() {
  const sections = cats.map((c) => {
    const cards = byCat[c.id].map((t) =>
      `<a class="tool-card" data-name="${esc((t.name + " " + t.short).toLowerCase())}" href="/${t.path}"><b>${esc(t.name)}</b><span>${esc(t.short)}</span></a>`
    ).join("\n        ");
    return `<section class="cat-section">
      <div class="cat-head">
        <h2><a href="/${c.id}">${esc(c.label)}</a></h2>
        <p>${esc(c.blurb)}</p>
      </div>
      <div class="grid">
        ${cards}
      </div>
    </section>`;
  }).join("\n    ");

  const body = `<main class="wrap">
    <section class="hero">
      <h1>Every file tool you need.<br>None of your files leave the browser.</h1>
      <p>Convert images, work with PDFs, and debug data formats, fast, free, and private. There is no server: your files are processed on your own device.</p>
      <span class="trust-badge">${ICONS.shield} No uploads · No accounts · Open source</span>
    </section>
    <div class="header-search" style="max-width:430px;margin:18px 0 6px">
      ${ICONS.search}
      <input type="text" id="grid-search" placeholder="Search ${tools.length} tools..." aria-label="Search tools" style="width:100%">
    </div>
    <p class="no-results">No tools match that search.</p>
    <section class="cat-section" id="recent-tools" style="display:none">
      <div class="cat-head"><h2>Recently used</h2></div>
      <div class="grid"></div>
    </section>
    ${sections}
  </main>`;

  return page({
    title: "Convertze, Free Online File & Developer Tools. No Upload, Private.",
    desc: "Free in-browser tools: convert and compress images, merge and split PDFs, format JSON, decode JWTs and more. No uploads, no accounts, everything runs locally.",
    canonicalPath: "",
    body
  });
}

/* ---------- Category hubs ---------- */
function hubPage(cat) {
  const cards = byCat[cat.id].map((t) =>
    `<a class="tool-card" href="/${t.path}"><b>${esc(t.name)}</b><span>${esc(t.short)}</span></a>`
  ).join("\n      ");
  const others = cats.filter((c) => c.id !== cat.id)
    .map((c) => `<a href="/${c.id}">${esc(c.label)}</a>`).join(" · ");
  const body = `<main class="wrap">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> › ${esc(cat.label)}</nav>
    <h1 class="tool-h1">${esc(cat.label)}</h1>
    <p class="tool-tagline">${esc(cat.blurb)}</p>
    ${privacyBadge}
    <div class="grid" style="margin-top:8px">
      ${cards}
    </div>
    <p style="margin-top:26px;color:var(--muted);font-size:13.5px">More: ${others}</p>
  </main>`;
  return page({
    title: `${cat.label}, Free, Online, No Upload | Convertze`,
    desc: cat.blurb + " Free and private, no uploads, no sign-up.",
    canonicalPath: cat.id,
    activeCat: cat.id,
    body
  });
}

/* ---------- Tool pages ---------- */
const STEPS = {
  images: [
    "Drop one or more images, they stay on your device.",
    "Pick your options and convert.",
    "Download the result; multiple files arrive as a single zip."
  ],
  pdf: [
    "Drop your file(s), they are read locally, never uploaded.",
    "Set the options you need and run the tool.",
    "Download the finished PDF, images or text."
  ],
  dev: [
    "Paste your input, or drop a text file onto the box.",
    "The output updates live as you type.",
    "Copy it to the clipboard, or download it as a file."
  ]
};

function toolPage(t) {
  const cat = cats.find((c) => c.id === t.cat);
  const siblings = byCat[t.cat].map((s) =>
    `<a href="/${s.path}"${s.path === t.path ? ' aria-current="true"' : ""}>${esc(s.name)}</a>`
  ).join("\n        ");
  const related = (t.related || []).filter((p) => byPath[p]).map((p) =>
    `<li><a href="/${p}">${esc(byPath[p].name)}</a> <span style="color:var(--muted);font-weight:400">- ${esc(byPath[p].short)}</span></li>`
  ).join("\n          ");
  const steps = STEPS[t.cat].map((s) => `<li>${esc(s)}</li>`).join("\n          ");
  const libScripts = (t.libs || []).map((l) => LIB_URLS[l]);
  const jsonLd = JSON.stringify({
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: t.name,
    url: `${SITE}/${t.path}`,
    description: t.metaDescription,
    applicationCategory: "UtilitiesApplication",
    operatingSystem: "Any",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }
  });

  const body = `<main class="wrap">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> › <a href="/${cat.id}">${esc(cat.label)}</a> › ${esc(t.name)}</nav>
    <h1 class="tool-h1">${esc(t.h1)}</h1>
    <p class="tool-tagline">${esc(t.short)}</p>
    ${privacyBadge}
    <div class="page-grid">
      <div>
        <div class="panel" id="tool-root" data-tool="${t.path}">
          <noscript>This tool runs entirely in your browser and needs JavaScript enabled.</noscript>
          <p style="color:var(--muted);font-size:13.5px;margin:0">Loading tool...</p>
        </div>
        <div class="panel about">
          <h2>About this tool</h2>
          ${t.about.map((p) => `<p>${esc(p)}</p>`).join("\n          ")}
        </div>
        <div class="panel">
          <h2>How it works</h2>
          <ol class="steps">
          ${steps}
          </ol>
        </div>
        <div class="panel">
          <h2>Related tools</h2>
          <ul class="related-list">
          ${related}
          </ul>
        </div>
      </div>
      <aside class="side-nav" aria-label="${esc(cat.label)}">
        <h3>${esc(cat.label)}</h3>
        ${siblings}
      </aside>
    </div>
  </main>
  <script type="application/ld+json">${jsonLd}</script>`;

  return page({
    title: `${t.name}, Free, Online, No Upload | Convertze`,
    desc: t.metaDescription,
    canonicalPath: t.path,
    activeCat: t.cat,
    body,
    scripts: [...libScripts, "/assets/" + CAT_MODULE[t.cat]]
  });
}

/* ---------- 404 ---------- */
function notFound() {
  const body = `<main class="wrap">
    <div class="err-page">
      <h1>404</h1>
      <p>That page doesn't exist, but the tool you wanted probably does.</p>
      <div class="header-search" data-tool-search>
        ${ICONS.search}
        <input type="text" placeholder="Search tools..." aria-label="Search tools">
        <div class="search-pop"></div>
      </div>
      <p style="margin-top:18px"><a class="btn" href="/">Browse all tools</a></p>
    </div>
  </main>`;
  return page({
    title: "Page not found, Convertze",
    desc: "That page doesn't exist. Search Convertze's free in-browser file and developer tools.",
    canonicalPath: "404.html",
    body
  });
}

/* ---------- Sitemap ---------- */
function sitemap() {
  const urls = [
    { loc: `${SITE}/`, pri: "1.0" },
    ...cats.map((c) => ({ loc: `${SITE}/${c.id}`, pri: "0.9" })),
    ...tools.map((t) => ({ loc: `${SITE}/${t.path}`, pri: "0.8" }))
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${TODAY}</lastmod>
    <priority>${u.pri}</priority>
  </url>`).join("\n")}
</urlset>
`;
}

/* ---------- main ---------- */
function write(rel, content) {
  const file = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  console.log("wrote " + rel);
}

write("index.html", homepage());
for (const c of cats) write(path.join(c.id, "index.html"), hubPage(c));
for (const t of tools) write(path.join(t.path, "index.html"), toolPage(t));
write("404.html", notFound());
write("sitemap.xml", sitemap());
console.log(`done: 1 home + ${cats.length} hubs + ${tools.length} tool pages + 404 + sitemap`);
